name: cart_rent
description: Ứng dụng gọi xe Bích Long

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_storage: ^4.0.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.1+2
  uuid: ^2.2.2
  url_launcher: ^5.5.3
  google_maps_flutter: ^1.0.2
  email_validator: ^1.0.6
  image_picker: ^0.6.7+12



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

